### ISSUE TITLE
주제 선정

### ISSUE THREAD

**Issue by swjung0826** [daahunii/DVM_project#1]
CRUD 주제 목록

CAFE 디저트 자판기
출퇴근 관리 시스템
스터디 카페 예약 시스템
가계부 프로그램
교내 라운지 예약 시스템
음료 자판기
등등...

**Comment by daahunii** [comment]
어떤 주제로 만드는게 좋을까?

**Comment by daahunii** [comment]
내 생각에는 음료 자판기를 CRUD로 만들면 간단하게 만들 수 있을 것 같아

**Comment by swjung0826** [comment]
좋아좋아 함수 구현하기에도 좋을 것 같네!!

**Comment by daahunii** [comment]
Okay!
